server:
  port: 10088
  tomcat:
    uri-encoding: UTF-8
    max-threads: 200 #最大工作线程数量800
    min-spare-threads: 20 #最小工作线程数量 20
    max-connections: 10000 #一瞬间最大支持的并发的连接数
    accept-count: 200 #等待队列长度
  servlet:
    session:
      timeout: 30
    context-path: /api
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/candeus-product?serverTimezone=GMT%2B8&allowMultiQueries=true&autoRec&characterEncoding=utf-8&useSSL=false
    username: root
    password: root #自己的数据库密码
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: localhost
    port: 6379
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s
minio:
  endpoint: http://localhost:9000
  accessKey: accessKey
  secretKey: secretKey
  bucketName: bucketName

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl